#!/bin/sh
#
#

NODE=esess
HOST=local
APP=esess
APP_CTL=esses
CONFIG="env/esess"
PA_DIRS="-pa ebin -pa deps/*/ebin"
TITLE="esses node start"

if [ "" = "$HOST | grep '\.'" ] ;then
  TYPE="sname"
  else
    TYPE="name"
    fi

ERL="erl +A 2 +K true  "

start()
{
	echo $TITLE
	$ERL\
	$PA_DIRS \
	-kernel error_logger '{file, "./log/erlang.log"}' \
	-boot start_sasl \
	-config $CONFIG \
	-s $APP \
	-$TYPE $NODE@$HOST \
	-noinput -detached
}


debug()
{
	echo $TITLE
	$ERL \
	$PA_DIRS \
	-boot start_sasl \
	-config $CONFIG \
	-s reloader \
	-s $APP \
	-$TYPE $NODE@$HOST 
}

shell()
{
    $ERL \
    -$TYPE debug$NODE@$HOST \
    $PA_DIRS \
    -config $CONFIG \
    -hidden \
    -remsh $NODE@$HOST
}

stop()
{
	#ctl stop
	ctl stop_node
	#pkill -TERM -f "$NODE@$HOST" && echo "Process has been terminated"
	pkill -KILL -f "$NODE@$HOST" && echo "Process has been killed"	
	echo "Application has been stopped"
}

restart()
{
	stop
	sleep 2
	start
}


reload()
{
	ctl reload_node
	echo "Application has been reloaded"
}


ctl()
{
    $ERL \
    -name ctl$NODE@$HOST \
    $PA_DIRS \
    -hidden \
    -noinput \
    -s $APP_CTL \
    -extra $NODE@$HOST $@
}



usage(){
	echo "$0 {start|stop|debug|restart|shell|reload}"
}

[ $# -lt 1 ] && usage

$@

